return {
  {
    {nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, "black", "black", nil, nil, nil, nil, nil, nil, "black", "gray", "gray", "purple", nil, nil},
    {nil, nil, nil, "purple", "purple", nil, nil, nil, nil, nil, "purple", "purple", "purple", nil, nil, nil},
    {nil, nil, nil, nil, "purple", "black", nil, nil, nil, "black", "purple", "purple", nil, nil, nil, nil},
    {nil, "black", nil, nil, "purple", "gray", nil, nil, nil, "gray", "purple", "purple", nil, nil, nil, nil},
    {nil, "black", nil, nil, "purple", "purple", "black", nil, nil, "purple", "gray", nil, nil, nil, "gray", nil},
    {nil, "black", "gray", "gray", nil, "black", "gray", nil, "black", "purple", "black", "black", "black", "black", "black", nil},
    {nil, "black", "black", nil, "gray", "gray", "purple", nil, "gray", "gray", "black", "purple", "black", "purple", "black", nil},
    {nil, "black", "black", "gray", "gray", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", nil},
    {nil, nil, "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", nil},
    {nil, nil, "black", "black", "black", "black", "black", "black", "black", "black", nil, nil, nil, nil, nil, nil},
    {nil, nil, "black", "black", "black", "black", "black", "black", "black", "black", nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, "black", "black", "black", "black", "black", nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, "black", "black", nil, "black", "black", nil, nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, "black", "black", "black", "black", "black", nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil},
  },
  {
    {nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "black", "gray", "black", nil},
    {nil, nil, "black", "purple", "gray", nil, nil, nil, nil, nil, "gray", "purple", "purple", "black", nil, nil},
    {nil, nil, nil, "black", "purple", "black", nil, nil, nil, nil, "purple", "purple", "purple", nil, nil, nil},
    {nil, "black", nil, nil, "purple", "gray", nil, nil, nil, "black", "purple", "purple", "black", nil, nil, nil},
    {nil, "black", nil, nil, "purple", "purple", nil, nil, nil, "gray", "gray", "black", nil, nil, "gray", nil},
    {nil, "black", "gray", "gray", nil, "purple", "black", nil, nil, "gray", "black", "black", "black", "black", "black", nil},
    {nil, "black", "black", nil, "gray", "gray", "gray", nil, "gray", "gray", "black", "purple", "black", "purple", "black", nil},
    {nil, "black", "black", "gray", "gray", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", nil},
    {nil, nil, "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", nil},
    {nil, nil, "black", "black", "black", "black", "black", "black", "black", "black", nil, nil, nil, nil, nil, nil},
    {nil, nil, "black", "black", "black", "black", "black", "black", "black", "black", nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, "black", "black", "black", "black", "black", nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, "black", "black", nil, "black", "black", nil, nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, "black", "black", "black", "black", "black", nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil},
  },
  {
    {nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, "black", "black", nil, nil, nil, nil, nil, nil, "black", "gray", "gray", "purple", nil, nil},
    {nil, nil, "black", "purple", "gray", nil, nil, nil, nil, "black", "purple", "purple", "purple", nil, nil, nil},
    {nil, "black", nil, "black", "purple", nil, nil, nil, nil, "black", "purple", "gray", nil, nil, nil, nil},
    {nil, "black", nil, nil, "purple", "gray", "black", nil, nil, "gray", "gray", "purple", nil, nil, "gray", nil},
    {nil, "black", "gray", "gray", "purple", "purple", nil, nil, nil, "purple", "black", "black", "black", "black", "black", nil},
    {nil, "black", "black", nil, "gray", "gray", "black", nil, "gray", "gray", "black", "purple", "black", "purple", "black", nil},
    {nil, "black", "black", "gray", "gray", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", nil},
    {nil, nil, "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", nil},
    {nil, nil, "black", "black", "black", "black", "black", "black", "black", "black", nil, nil, nil, nil, nil, nil},
    {nil, nil, "black", "black", "black", "black", "black", "black", "black", "black", nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, "black", "black", "black", "black", "black", nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, "black", "black", nil, "black", "black", nil, nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, "black", "black", "black", "black", "black", nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil},
  },
  {
    {nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil},
    {nil, "black", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil},
    {nil, "black", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, "black", nil, "black", nil},
    {nil, "black", "black", "black", nil, nil, nil, nil, nil, nil, "gray", "black", "black", nil, "gray", nil},
    {nil, "black", "gray", "gray", nil, nil, nil, nil, nil, nil, "black", "black", "black", "black", "black", nil},
    {nil, "black", "black", nil, "gray", "gray", "black", nil, "gray", "gray", "black", "purple", "black", "purple", "black", nil},
    {nil, "black", "black", "gray", "gray", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", nil},
    {nil, nil, "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", nil},
    {nil, nil, "black", "black", "black", "black", "black", "black", "black", "black", nil, "black", "black", nil, "purple", nil},
    {nil, nil, "black", "black", "black", "black", "black", "black", "black", "black", nil, nil, nil, nil, "black", nil},
    {nil, nil, nil, nil, "black", "black", "black", "black", "black", nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, "black", "black", nil, "black", "black", nil, nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, "black", "black", "black", "black", "black", nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil},
  },
  {
    {nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil},
    {nil, "black", nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil},
    {nil, "black", nil, nil, nil, nil, nil, nil, nil, nil, "gray", nil, nil, nil, "gray", nil},
    {nil, "black", "gray", "gray", nil, nil, nil, nil, nil, nil, "black", "black", "black", "black", "black", nil},
    {nil, "black", "black", "purple", "gray", "gray", "black", nil, "gray", "gray", "black", "purple", "black", "purple", "black", nil},
    {nil, "black", "black", "gray", "gray", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", nil},
    {nil, nil, "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", nil},
    {nil, nil, "black", "black", "black", "black", "black", "black", "black", "black", nil, nil, nil, nil, nil, nil},
    {nil, nil, "black", "black", "black", "black", "black", "black", "black", "black", nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, "black", "black", "black", "black", "black", nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, "black", "black", nil, "black", "black", nil, nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, "black", "black", "black", "black", "black", nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil},
  },
  {
    {nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, nil, nil, nil, nil, "black", "purple", "purple", "purple", nil, nil, nil, nil},
    {nil, "black", nil, "purple", "purple", nil, nil, nil, "black", "purple", "purple", "black", nil, nil, nil, nil},
    {nil, "black", nil, "black", "purple", nil, nil, nil, nil, "purple", "gray", "black", nil, nil, "gray", nil},
    {nil, "black", "gray", "gray", "gray", "black", nil, nil, nil, "black", "black", "black", "black", "black", "black", nil},
    {nil, "black", "black", nil, "gray", "gray", nil, nil, "gray", "gray", "black", "purple", "black", "purple", "black", nil},
    {nil, "black", "black", "gray", "gray", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", nil},
    {nil, nil, "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", nil},
    {nil, nil, "black", "black", "black", "black", "black", "black", "black", "black", nil, nil, nil, nil, nil, nil},
    {nil, nil, "black", "black", "black", "black", "black", "black", "black", "black", nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, "black", "black", "black", "black", "black", nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, "black", "black", nil, "black", "black", nil, nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, "black", "black", "black", "black", "black", nil, nil, nil, nil, nil, nil, nil},
    {nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil},
  },
}
